# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest
steps:
  - checkout: self
    clean: true
    persistCredentials: true
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
  - task: ado-testingextension@2
    inputs:
      Operation: 'createTests'
      DevOpsUrl: 'https://dev.azure.com/rgcorp-projects'
      AzureProjectName: 'SampleDemo'
      PAT: '$(System.AccessToken)'
      DotnetExePath: 'dotnet'
      RepoName: 'test'
      FeatureFilePath: 'SpecFlowCalculator.Specs'
      AreTheseDotnetTests: 'true'